set_colores = ({"Rojo", "Blanco", "Azul"})
print(set_colores)
set_colores.update({"Violeta", "Dorado"})
print(set_colores)
set_colores.discard("Celeste")
set_colores.discard("Blanco")
set_colores.discard("Dorado")
print(set_colores)